server:
  port: 8088
  servlet:
    session:
      timeout: 1000m

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tournament?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true

  main:
    banner-mode: off

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  path: data
  avatars: avatars
  logs: logs


#  mvc:
#    static-path-pattern: /resources/static/**
